stellar/slingshot

zkvm/src/errors.rs
zkvm/src/ops.rs
zkvm/src/types.rs
zkvm/src/vm.rs

Uses the `SignedInteger` type from spacesuit and fills in the witness and assignment fields for cloak variables.

zkvm/vm: add witness fields and assignments for cloak variables

---

zkvm/src/ops.rs
zkvm/src/prover.rs
zkvm/src/txlog.rs
zkvm/src/types.rs
zkvm/src/verifier.rs
zkvm/src/vm.rs

Implements the `Delegate` and `RunTrait` traits needed by the VM for the prover. Also implements the `build_tx` function, minus the code to actually encode a prover's `Instruction` into tx bytecode for the verifier.

zkvm/prover: implement traits and build_tx for prover

---

zkvm/spec/ZkVM.md

* Clarifies that Value's qty and flv are _variables_, not _scalars_.
* Clarifies the `reblind` instruction: `V1` commitment is read from the internals of the variable `var1`.
* Discussion of the inequality constraints (`<,≤,>,≥`).
* Discussion of the logical `not` constraint.
* Discussion of the txid / utxo uniqueness and comparison with TxVM.
* To avoid confusion with cryptographic "witness" data (secret quantities, blinding factors, private keys etc), "Tx Witness" is renamed to "Tx object". This also matches the current API as it's implemented.

zkvm: spec clarification and expanded rationale

---

zkvm/src/encoding.rs
zkvm/src/ops.rs
zkvm/src/predicate.rs
zkvm/src/types.rs
zkvm/src/vm.rs

Implements part of #61, to serialize the Prover's vec of Instructions into bytecode for the Verifier.
WIP: a few pieces missing around how best to implement Data `to_bytes` and `len`, as well as how to get the previous txID needed for `Input`

zkvm/prover: serialize instructions to bytecode

---

zkvm/src/point_ops.rs
zkvm/src/predicate.rs
zkvm/src/prover.rs
zkvm/src/signature.rs
zkvm/src/types.rs
zkvm/src/verifier.rs
zkvm/src/vm.rs

First pass at the suggestion in https://github.com/interstellar/slingshot/pull/74, to move the `CompressedRistretto` representation of a predicate into the struct

zkvm/predicate: move point into Predicate struct

---

zkvm/spec/ZkVM.md

Clarifying the spec. 
Closes #71.

ZkVM: addressing spec feedback

---

slidechain/custodian.go
slidechain/export.go
slidechain/export_test.go
slidechain/import.go
slidechain/mockhorizon/mockhorizon.go
slidechain/slidechain_test.go
slidechain/stellar/tx.go

Adds the `mockhorizon` package, defining a mock Horizon interface to use in place of making real calls to Horizon for unit tests (currently, `TestPegOut`). The integration test, `TestEndToEnd`, still calls out to a real Horizon server.

slidechain/mockhorizon: use mock horizon in unit tests

---

zkvm/src/contract.rs
zkvm/src/encoding.rs
zkvm/src/errors.rs
zkvm/src/lib.rs
zkvm/src/predicate.rs
zkvm/src/transcript.rs
zkvm/src/types.rs
zkvm/src/vm.rs

This allows decoupling parsing of the input from constructing a Contract instance and allocating necessary variables for the stored Values. The single method to convert FrozenContract into Contract becomes shared between Prover and Verifier.
* Contract-related code is moved to `contract.rs`
* `Input` and `InputWitness` are merged in one type `Input` which is constructed both by the Prover and Verifier when parsing the input string.
* Serialization code for inputs and outputs is grouped together in `contract.rs`
Closes #72.

ZkVM: decode input string into Input object instead of directly into Contract

---

zkvm/src/types.rs
zkvm/src/verifier.rs

This adds conversion from specific witness types into Data and DataWitness and makes DataWitness support integers and closed commitments (which is valid for reblinding scenarios). Also removes `ensure_closed` as unnecessary.

zkvm: complete data witness conversion methods

---

slidechain/export.go
slidechain/schema.go

Deletes rows that have been successfully processed (either success or nonretriable failure) from the `exports` table. We now only process rows that have not been pegged yet or have failed with a retriable error.
https://trello.com/c/5awzmfR4

slidechain: delete processed exports

---

zkvm/src/contract.rs
zkvm/src/encoding.rs
zkvm/src/errors.rs
zkvm/src/ops.rs
zkvm/src/types.rs
zkvm/src/verifier.rs
zkvm/src/vm.rs

Rename `Subslice` to `SliceReader` and change API for safer subslice parsing.
Fixes #80

zkvm/encoding: safer subslice parsing

---

slidechain/cmd/peg/peg.go
slidechain/cmd/slidechaind/slidechaind.go
slidechain/custodian.go
slidechain/export.go
slidechain/import.go
slidechain/record.go
slidechain/slidechain_test.go
slidechain/watch.go

Adds a peg-out `struct`, in lieu of creating very similar but different `struct`s meant to hold information about a peg-out. Also renames several functions to refer specifically to peg-ins to avoid confusion.

slidechain: add peg-out struct

---

slidechain/cmd/export/export.go
slidechain/export.go
slidechain/export_test.go
slidechain/schema.go
slidechain/slidechain_test.go
slidechain/watch.go

Differentiates the uses of `temp` across the slidechain export logic. We currently use it interchangeably to refer to differently typed representations of the preauthorization transaction's temporary account ID. Instead, variable names are changed to make their types clearer.

slidechain: differentiate uses of temp

---

spacesuit/src/mix.rs
spacesuit/src/value.rs

Adds `checked_add` and `checked_mul` to check overflow on `SignedInteger`
Part of #91

spacesuit: checked arithmetic for SignedInteger

---

slidechain/cmd/export/export.go
slidechain/export.go
slidechain/schema.go
slidechain/slidechain_test.go

Simplifies checking for the export tx on TxVM in `cmd/export`: rather than repeatedly checking new blocks for the tx, it simply calls the `wait` logic within the `submit` endpoint. Renames `mustDecode` to `mustDecodeHex`, in line with the rest of the codebase. De-exports the `isExportTx` check.

slidechain: clean up export cmd

---

slidechain/export.go
slidechain/slidechain_test.go

Tests different amounts for input and export in the end-to-end test. Simplifies check for export tx to use `wait` logic in submission, instead of a hand-rolled function.

slidechain: test different input and export amounts

---

zkvm/src/vm.rs

Bug was introduced at: https://github.com/interstellar/slingshot/commit/a6e3bcf49b79b4dba2adc0a9241b5766ed105c46#r32435898 (PR #81)

zkvm: check the result and return err instead of ignoring it

---

zkvm/src/contract.rs
zkvm/src/errors.rs
zkvm/src/lib.rs
zkvm/src/predicate.rs
zkvm/src/prover.rs
zkvm/src/signature.rs
zkvm/src/types.rs
zkvm/src/verifier.rs
zkvm/src/vm.rs
zkvm/tests/zkvm.rs

1. Makes conversion from predicate witness to predicate non-failable, so we can use From/Into traits.
2. Clarifies distinction between the opaque predicate (as viewed by the Verifier) and opaque witness for a predicate (an opaque branch in a predicate tree as viewed by the Prover).

zkvm: revamp the predicate type

---

spacesuit/README.md
spacesuit/src/lib.rs
spacesuit/src/value.rs

This enforces documentation for all exported items in spacesuit.

spacesuit: deny missing docs

---

keytree/keytree.md

This adds a draft of a spec. It's a good new-to-Rust issue to implement (in a separate PR).

keytree: new package for key derivation scheme with Ristretto and Merlin

---

zkvm/src/contract.rs
zkvm/src/ops.rs
zkvm/src/predicate.rs
zkvm/src/types.rs
zkvm/src/vm.rs

Computes exact serialized length for `Data` witness types, rather than providing a lower bound.
Fixes #116

zkvm/types: compute exact serialized length

---

zkvm/src/constraints.rs
zkvm/src/prover.rs
zkvm/src/vm.rs
zkvm/tests/zkvm.rs

Per #122 this de-emphasizes `CommitmentWitness` and moves all the API to `Commitment`.

zkvm: streamline Commitment API

---

zkvm/src/constraints.rs
zkvm/src/contract.rs
zkvm/src/lib.rs
zkvm/src/predicate.rs
zkvm/src/scalar_witness.rs
zkvm/src/types.rs
zkvm/src/vm.rs

1. Renames `FrozenContract` to `Output`.
2. Makes other `Frozen*` types private.
3. Moves freezing/unfreezing logic into `contract.rs`.
4. Revisits private/pub(crate) methods.
5. Writing API is streamlined via `encoding::write_*` methods, so we can later remove assumption of `&mut Vec<u8>` and use generic `Writer` trait to make code cleaner and assuming less.
Closes #122.

zkvm: refactor Input/Contract serialization logic

---

zkvm/src/lib.rs
zkvm/src/prover.rs
zkvm/src/txlog.rs
zkvm/src/verifier.rs
zkvm/src/vm.rs
zkvm/tests/zkvm.rs

Adds `TxHeader` type, used in `Tx`, `VerifiedTx`, `TxLog::Entry`, and `build_tx` 
Fixes #132

zkvm/vm: add TxHeader type

---

zkvm/src/lib.rs
zkvm/src/types.rs

Collapses the DataWitness type into Data
Fixes #135

zkvm/types: collapse DataWitness type

---

slidechain/cmd/export/export.go
slidechain/cmd/peg/peg.go

Streamlines amount and asset parsing in `cmd/export` and `cmd/peg`.

slidechain: streamline parsing in export and peg cmds

---

zkvm/docs/zkvm-spec.md
zkvm/src/constraints.rs
zkvm/src/errors.rs
zkvm/src/types.rs
zkvm/src/vm.rs

- change `Constraint::{And, Or}` to be a tuple of two boxed constraints, instead of a vector (since they'll only ever be created from two constraints anyways, and we can do the flattening in the `verify` function
- implement `and`, `or` using the new Constraint type
- implement `verify`: enter 2nd phase of 2-phase challenge API, in order to get `z` challenge. Then recursively "flatten" the constraint, until the base case `Expression` type, and combine the `Expression`s according to the rules until you have one `Expression` that represents the whole constraint. Then push that constraint onto the constraint system.
Question: I implemented the `From<R1CSError> for VMError` trait, but in `verify` it does not automatically convert `R1CSError` to `VMError`, so I have to do it explicitly. I …

zkvm: implement `and`, `or`, `verify` instructions

---

.travis.yml
check-markdown-links.rb
keytree/keytree.md
slidechain/Running.md
spacesuit/spec.md
spacesuit/src/cloak.rs
zkvm/README.md
zkvm/docs/zkvm-api.md
zkvm/docs/zkvm-spec.md

This adds a script that checks that most references in the specs are valid:
1. Checks all the local anchors within each `.md` file.
2. Checks all cross-file references and anchors between `.md` files.
3. Checks if remote URLs are loadable (pings `http(s)://` links).
4. Travis checks these on each PR.
5. `/vendor/` paths are ignored.
1. The title-to-anchor convertor is ad-hoc and may not produce the same result as Github/Markdown, so this may turn into false negatives or false positives.
2. Links to anchors to remote pages are not fully checked: only the URL is pinged, but the anchor within it is not verified (so it may become stale).
3. Remote URLs may die causing your PRs be rejected by Travis. In such case it's a good opportunity to fix the URLs or revisit the strictness of the script.

slingshot: check all the markdown references

---

zkvm/docs/zkvm-spec.md
zkvm/src/contract.rs
zkvm/src/ops.rs
zkvm/src/types.rs
zkvm/src/vm.rs
zkvm/tests/zkvm.rs

Adds a metadata `Data` as input to the `issue` command, embedding metadata in the flavor

zkvm/vm: embed metadata in flavor

---

zkvm/src/constraints.rs
zkvm/src/contract.rs
zkvm/src/errors.rs
zkvm/src/lib.rs
zkvm/src/ops.rs
zkvm/src/prover.rs
zkvm/src/signature.rs
zkvm/src/transcript.rs
zkvm/src/txlog.rs
zkvm/src/types.rs
zkvm/src/verifier.rs
zkvm/src/vm.rs

This enforces presence of documentation for all items (modules, types, traits, methods, constants) throughout ZkVM.
It allows opt-out via per-item `#[allow(missing_docs)]`. I use it in two places for lists of opcodes and instructions where explicit documentation is not more helpful than the name of an instruction itself: the reader is supposed to check the specification instead.
Closes #114.

zkvm: deny(missing_docs)

---

token/src/lib.rs
token/src/token.rs

For the follow up fixes: we can remove import of `Instruction` if we use `Program` throughout instead of raw `Vec<Instruction>`.

token: fix warnings

---

slidechain/export.go
slidechain/watch.go

Checks for the export transaction more robustly. A log statement is added to the called export contract, and the goroutine watching for the export transaction also checks for the existence of the accompanying tuple in the transaction log.

slidechain: check for export tx more robustly

---

zkvm/src/types.rs

This makes `to_program` consistent with `to_predicate`, `to_commitment` and `to_input`.

zkvm: convert data `to_program` by taking opaque representation into account too

---

README.md
token/src/token.rs
zkvm/docs/zkvm-api.md
zkvm/docs/zkvm-spec.md
zkvm/src/constraints.rs
zkvm/src/contract.rs
zkvm/src/lib.rs
zkvm/src/ops.rs
zkvm/src/txlog.rs
zkvm/src/types.rs
zkvm/src/vm.rs
zkvm/tests/zkvm.rs

Per #177, cleans up all infrastructure for reblinding of commitments. 
* `Value` has raw commitments, not `Variable`s. 
* `Output` is removed in favor of `Contract`.
* `FrozenItem` is removed in favor of `PortableItem`.
* `FrozenValue` is removed in favor of `Value`.
* `freeze`/`unfreeze` methods removed from Contract/Output.
* "attachment" terminology is removed, instead we "commit zkvm variables to R1CS" when we need R1CS variables.
* `VariableCommitment` type and array of such items is removed from VM state.
* `Variable` type is now a pair of commitments (can be made portable later if needed).
* `unblind` instruction is left unchanged.

zkvm: remove blinding protocol + simplify VM

---

token/src/token.rs
zkvm/src/ops.rs
zkvm/src/predicate.rs
zkvm/src/prover.rs
zkvm/src/types.rs
zkvm/tests/zkvm.rs

cleaning up instances of `Vec<Instruction>`, replacing with `Program`
Fixes #182

zkvm/ops: replace instances of `Vec<Instruction>` with `Program`

---

slidechain/Running.md

Updates the running spec to include the required `bcid` flag for the peg-in command.

slidechain: add bcid requirement to running spec

---

check-markdown-links.rb
token/src/token.rs
zkvm/docs/zkvm-spec.md
zkvm/src/contract.rs
zkvm/src/errors.rs
zkvm/src/lib.rs
zkvm/src/txlog.rs
zkvm/src/types.rs
zkvm/src/vm.rs
zkvm/tests/zkvm.rs

This introduces **anchors** and **contract IDs**, bringing back good ideas from TxVM, but doing it slightly differently. 
1. Each contract has a globally unique identifier, **contract ID**, which allows `delegate` to sign the unique instance in presence of reused predicate keys (see #172).
2. Uniqueness of contracts is provided by unique **anchors** contained within the contracts.
3. Nonce-based contracts have their anchor computed out of the nonce tuple `(predicate, blockid, exptime)`. Blockchain state machine tracks these nonce anchors to ensure their uniqueness.
4. UTXO ID is simply a contract ID.
5. Newly created contracts and outputs **consume VM's last anchor** and **set their ID as a new last anchor**.
6. Instead of a "uniqueness" flag, VM simply keeps and updates `Option<Anchor>`. …

zkvm: introduce anchors

---

zkvm/Cargo.toml
zkvm/docs/zkvm-spec.md
zkvm/src/encoding.rs
zkvm/src/lib.rs
zkvm/src/vm.rs

Implements serialization of Tx object. Closes #131 .

zkvm: serialize Tx object

---

slidechain/custodian.go
slidechain/stellar/account.go

Adds additional logging to display the friendbot response on failure (which includes the transaction XDR and failure codes, helpful for debugging)
New failure log:
```
slidechain_test.go:662: error funding address through friendbot. got bad status code 400, response {
"type": "https://stellar.org/horizon-errors/https://stellar.org/horizon-errors/transaction_failed",
"title": "Transaction Failed",
"status": 400,
"detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html",
"extras": {
"envelope_xdr": "AAAAABB90WssODNIgi6BHveqzxTRmIpvAFRyVNM+Hm2GVuCcAAAAZAAABD0AAb+mAAAAAAAAAAAAAAABAAAAAAAA …
```

slidechain: display whole response body with friendbot failure

---

keytree/keytree.md
keytree/src/lib.rs

This is Step 4 in https://github.com/interstellar/slingshot/pull/202#discussion_r263216987, 
working to make sure that intermediate key derivation isn't failable. 
This PR also updates the spec to match this change.

keytree: store precomputed transcripts on Xprv, Xpub

---

zkvm/docs/zkvm-spec.md
zkvm/src/constraints.rs
zkvm/src/ops.rs
zkvm/src/scalar_witness.rs
zkvm/src/vm.rs

Adds boolean `not` instruction. Modifies `Constraint.flatten` to also return an optional assignment, used to calculate the inputs for `not`.
Fixes #117

zkvm/constraints: adds boolean `not` instruction

---

keytree/src/lib.rs

This is my first stab at this function. A few outstanding questions: 
1. This function returns an Option because it calls a function that returns an Option and I wasn't sure what else to do.
2. Currently it only accepts Xpubs; I'd love a pointer on how to make it accept Xprvs too. I'm guessing something with generics? _has never see a generic before, :gopher:_
3. This note about not calling the Transcript directly has me a tad spooked: https://doc.dalek.rs/merlin/struct.Transcript.html#note
4. Is the function signature even right here? Among other things, I made it take a label which is a `&'static std::string::String` to satisfy some business about lifetimes.

keytree: derive intermediate pubkey

---

keytree/src/lib.rs

Addresses https://github.com/interstellar/slingshot/issues/179

keytree: add serialization for xpub, xprv

---

keytree/Cargo.toml
keytree/src/lib.rs

Per conversation with @oleganza, test data is more readable as a hex string (rather than a byte slice). This does introduce a bit more boilerplate around encoding and decoding, so I'm a bit apathetic on that.

keytree: express test data as hex strings

---

zkvm/src/errors.rs
zkvm/src/signature/counterparty.rs
zkvm/src/signature/mod.rs
zkvm/src/signature/multikey.rs
zkvm/src/signature/musig.rs
zkvm/src/signature/signature.md
zkvm/src/signature/signer.rs

MuSig work outline here:
https://github.com/interstellar/slingshot/issues/92

MuSig: add counterparties

---

zkvm/docs/zkvm-blockchain.md
zkvm/docs/zkvm-spec.md
zkvm/src/vm.rs

Updates `zkvm-spec.md` to use millisecond-based timestamps.

zkvm/docs: blockchain spec

---

spacesuit/benches/spacesuit.rs
spacesuit/src/mix.rs
spacesuit/src/range_proof.rs
spacesuit/src/shuffle.rs
spacesuit/tests/spacesuit.rs
zkvm/src/prover.rs
zkvm/src/verifier.rs

This tweaks the usage of r1cs::Prover/Verifier to the updated API in the `develop` branch of the Bulletproofs: https://github.com/dalek-cryptography/bulletproofs/pull/257
Folks, run `cargo update` if you have weird compilation errors (after merging this PR).

zkvm|spacesuit: fix for updated bulletproofs API

---

zkvm/docs/zkvm-blockchain.md

This adds a make-block procedure, refactors some other procedures, fixes the definition of txroot, discards the notion of an initial block (there is only an initial block _header_) and removes some overaggressive `mdfmt` line wrapping.

zkvm/docs: tweaks to the blockchain spec

---

spacesuit/README.md
zkvm/README.md

Add links to the old spacesuit and zkvm repos, for the sake of continuity and ability to reference old commits and issues.

spacesuit & zkvm: add backrefs to old repos

---

token/src/token.rs
zkvm/src/keys.rs
zkvm/src/verifier.rs
zkvm/tests/zkvm.rs

Removes the `key_agg_fn` closure in `Verifier::verify_tx` to make key aggregation consistent between Multikey and single-party Schnorr aggregation. 
Sparked by [this conversation](https://i10r.slack.com/archives/CEMSC5YRK/p1554331172056000) since we want all transactions to be verifiable without this extra per-tx information about which key aggregation scheme to use.

zkvm/key: use MuSig key aggregation scheme

---

token/src/token.rs
zkvm/docs/zkvm-blockchain.md
zkvm/docs/zkvm-spec.md
zkvm/src/blockchain/block.rs
zkvm/src/blockchain/errors.rs
zkvm/src/blockchain/state.rs
zkvm/src/contract.rs
zkvm/src/errors.rs
zkvm/src/ops.rs
zkvm/src/program.rs
zkvm/src/txlog.rs
zkvm/src/vm.rs
zkvm/tests/zkvm.rs

This removes nonces from the design. This dramatically simplifies blockchain state and validation rules: every tx must spend an input to be unique. Initial anchoring can be provided in a number of ways: pegged assets from a parent chain, and/or minted synthetic nonce-units at each block, etc. See #230 and #249 for details. To bootstrap anchoring, the initial block can start with an initial UTXO set (this API is necessary to have until we have minteable nonce-units (if at all), and even then it may be useful in its own right).
UTXO set commitment is changed to a normal merkle tree (instead of radix/patricia trie), in order to support utreexo (see #258). The state machine spec is still assuming presence of the entire set, this will be updated later.
Closes #262.
Closes #263.

zkvm: remove nonces

---

zkvm/docs/zkvm-blockchain.md

This change is necessitated by [the earlier change](https://github.com/interstellar/slingshot/pull/271) of utxoroot from a Merkle patricia tree hash (where ordering doesn't matter) to a Merkle binary tree hash.

zkvm/docs: utxo ordering now matters

---

zkvm/src/blockchain/state.rs
zkvm/src/contract.rs
zkvm/src/errors.rs
zkvm/src/lib.rs
zkvm/src/txlog.rs
zkvm/tests/zkvm.rs

Changes UTXO representation to match contract ID and implements `apply_txlog`, removing inputs and adding outputs to the UTXO set.

zkvm/blockchain: implement BlockchainState::apply_txlog

---

zkvm/src/blockchain/block.rs
zkvm/src/blockchain/state.rs
zkvm/src/contract.rs

Makes changes to use an ordered `Vec` for the UTXO set (per the spec change in #278), and implements computing the utxo and tx root.

zkvm/blockchain: compute utxo and tx root

---

musig/docs/musig-spec.md
zkvm/docs/zkvm-spec.md

This adds specification for signature protocols used in ZkVM with proper cross-references.

musig+zkvm: spec updates

---

spacesuit/Cargo.toml
spacesuit/src/cloak.rs
spacesuit/src/mix.rs
spacesuit/src/shuffle.rs
token/Cargo.toml
zkvm/Cargo.toml
zkvm/src/constraints.rs
zkvm/src/vm.rs

This PR in Bulletproofs changes the trait definitions, decoupling the randomization from general ConstraintSystem functionality: https://github.com/dalek-cryptography/bulletproofs/pull/270
Before it is merged (which is a breaking change), we need to update Spacesuit and ZkVM to use this API and merge that in lockstep with Bulletproofs.

zkvm+cloak: update for Bulletproofs API change #270

---

zkvm/docs/zkvm-spec.md
zkvm/src/constraints.rs
zkvm/src/errors.rs
zkvm/src/prover.rs
zkvm/src/vm.rs

Closes #252
Partly depends on https://github.com/dalek-cryptography/bulletproofs/pull/271 — if that PR 271 is merged, we can replace `PartialEq` implementation for `Expression` with a simple `#[derive(PartialEq)]`.

zkvm: implement guaranteed optimization for cleartext constraints

---

.travis.yml

We are not currently working on Slidechain actively, so it's fine to allow failures to not block other development due to Horizon's timeout issues. We can re-enable them again if/when we get back to it.

slidechain: make CI runs optional

---

zkvm/src/constraints.rs

This is a follow up to #287, based on the PartialEq added to upstream bulletproofs crate.

zkvm: remove unnecessary code via derive(PartialEq)

---

zkvm/docs/zkvm-spec.md
zkvm/src/ops.rs
zkvm/src/program.rs
zkvm/src/tx.rs
zkvm/src/vm.rs

We probably will use normal `issue`/`retire` instructions for pegging the external assets. If not, we could bring those back any time, but for now let's clean up the codebase from undesigned features.

zkvm: remove import/export instructions

---

zkvm/docs/zkvm-spec.md
zkvm/src/contract.rs
zkvm/src/ops.rs
zkvm/src/program.rs
zkvm/src/types.rs
zkvm/src/vm.rs
zkvm/tests/zkvm.rs

This adds a non-copyable type `Program` which is separate from `Data` type. Instructions `call` and `delegate` expect Program type, instruction `dup` fails if used with a Program.
Also, the `Expression` and `Constraint` are made non-copyable and non-droppable. Variables are left to be copyable, so they can participate in constraints and then be used in the construction of Values.
Rationale is covered in #301 & #306.
Closes #301
Closes #306

zkvm: non-copyable Program, Expression and Constraint

---

zkvm/src/blockchain/block.rs
zkvm/src/blockchain/tests.rs
zkvm/src/contract.rs
zkvm/src/merkle.rs
zkvm/src/predicate.rs
zkvm/src/program.rs
zkvm/src/prover.rs
zkvm/src/transcript.rs
zkvm/src/tx.rs
zkvm/src/types.rs
zkvm/src/utreexo/nodes.rs
zkvm/src/utreexo/tests.rs
zkvm/src/verifier.rs
zkvm/src/vm.rs
zkvm/tests/zkvm.rs

Also eliminates a couple of unused imports to silence all compiler warnings.

zkvm: use newer merlin api

---

keytree/keytree.md
keytree/src/lib.rs
keytree/src/tests.rs
keytree/src/transcript.rs
musig/docs/musig-spec.md
musig/src/context.rs
musig/src/signature.rs
musig/src/signer.rs
musig/src/transcript.rs
token/src/token.rs
zkvm/docs/utreexo.md
zkvm/docs/zkvm-blockchain.md
zkvm/docs/zkvm-spec.md

This replaces the use of deprecated methods in Merlin with better named methods.
Changes:
* `.commit_bytes()` to `.append_bytes()`
* `.commit_u64()` to `.append_u64()`
* `.commit_witness_bytes()` to `.rekey_with_witness_bytes()`

zkvm|musig|keytree|token: remove use of Merlin deprecated APIs

---

zkvm/src/blockchain/tests.rs
zkvm/src/contract.rs
zkvm/src/encoding.rs
zkvm/src/vm.rs
zkvm/tests/zkvm.rs

This patch removes premature optimization that keeps precomputed `ContractID`, which allows making the code and serialization simpler.

zkvm: simplify contract API

---

.travis.yml
accounts/Cargo.toml
accounts/src/lib.rs
accounts/src/tests.rs
keytree/Cargo.toml
keytree/src/lib.rs
zkvm/src/blockchain/block.rs
zkvm/src/contract.rs
zkvm/src/tx.rs
zkvm/src/types.rs
zkvm/src/utreexo/forest.rs
zkvm/src/utreexo/path.rs

* `accounts`: add Travis CI entry.
* `accounts`: refactors Receiver API to support serialization.
* `keytree`: suboptimal serialization for Xpub/Xprv.
* `zkvm`: serialize blocks and utreexo proofs.
Next steps: serialize BlockchainState, utreexo Forest and Catchup.

zkvm: more serde support

---

accounts/src/tests.rs
demo/src/main.rs
demo/src/nodes.rs
demo/src/records.rs
demo/src/schema.rs
demo/templates/network/mempool.html.tera
zkvm/src/blockchain/block.rs
zkvm/src/blockchain/mempool.rs
zkvm/src/blockchain/mod.rs
zkvm/src/blockchain/state.rs
zkvm/src/utreexo/forest.rs
zkvm/src/utreexo/path.rs
zkvm/src/utreexo/tests.rs

BIG CAVEAT: if app is rebooted, mempool is cleared. But if it was not empty, users' persistent state is left in inconsistent state. We'll fix it with persistent mempool, and then improve with expiring txs.

zkvm: mempool implementation

---

accounts/src/tests.rs
zkvm/src/blockchain/state.rs
zkvm/src/blockchain/tests.rs
zkvm/src/lib.rs
zkvm/src/merkle.rs
zkvm/src/predicate.rs
zkvm/src/tx.rs
zkvm/src/utreexo/forest.rs
zkvm/src/utreexo/heap.rs
zkvm/src/utreexo/mod.rs
zkvm/src/utreexo/path.rs
zkvm/src/utreexo/tests.rs

Important: this replaces broken encoding for Predicate CallProof, reusing the same format as for Utreexo proofs. Previous implementation did not have explicit length of neighbors (those were derived from the lower bits of the position, ignoring high zero bits).

zkvm: clean up merkle tree codebase, remove redundancy

---

zkvm/docs/zkvm-spec.md
zkvm/src/debug.rs
zkvm/src/errors.rs
zkvm/src/types.rs
zkvm/src/vm.rs

Fees are cleartext values paid via the `fee` instruction. Previous version of the instruction was inspecting the `Value` type, which was created by a `cloak` instruction, where a rangeproof was wasted needlessly. In this PR we reverse the order of the operations: first, the fee is borrowed and immediately written to txlog, then a `WideValue` with negative fee is left on stack to be mixed with other assets using `cloak`. This way, cloak does not need to have special support for cleartext values.

zkvm: redesigned fee operation to return WideValue and save a rangeproof

---

zkvm/docs/zkvm-spec.md
zkvm/src/errors.rs
zkvm/src/ops.rs
zkvm/src/types.rs
zkvm/src/vm.rs
zkvm/tests/zkvm.rs

Fixes https://github.com/stellar/slingshot/issues/406
The Program/Expression/Constraint are safe to drop types, but not safe to copy due to DoS risk. This was not implemented since we used a single category of "copyable types" for both copying and dropping. This patch introduces another category of "droppable types".
Specifically, Expression should be allowed to be dropped because of the `range` instruction that leaves it on stack. If one needs an inequality check, the left-on-stack expression must be dropped to clear the stack. In turn, `range` cannot consume the expression because then it cannot be used in downstream expressions, and we cannot allow copying for expressions for the DoS reasons.
Constraint and Program are also permitted to be dropped as there is no reason to prohibit …

zkvm: allow dropping Program/Expression/Constraint

---

accounts/src/tests.rs
blockchain/src/block.rs
blockchain/src/lib.rs
blockchain/src/mempool.rs
blockchain/src/protocol.rs
blockchain/src/state.rs
blockchain/src/tests.rs
demo/src/handlers.rs
demo/src/mempool.rs
demo/templates/network/status.html.tera
starsig/src/lib.rs
zkvm/docs/zkvm-blockchain.md
zkvm/src/encoding.rs
zkvm/src/lib.rs
zkvm/src/merkle.rs
zkvm/src/tx.rs

This patch introduces a `BlockTx` type: that encapsulates `Tx` with its utxo proofs. The block header commits to that object, making all the proofs and signatures authenticated by the block header, eliminating DoS vector during block processing. Also the blockchain state and mempool are simplified.

blockchain: witness hash for BlockTx and revamped state machine logic

---

zkvm/src/fees.rs
zkvm/src/program.rs

zkvm: add Program::fee builder and FeeRate utility methods

---

blockchain/src/utreexo/forest.rs
blockchain/src/utreexo/tests.rs
zkvm/docs/zkvm-stubnet.md
zkvm/src/tx.rs

This adds a non-mutating `Forest::verify` method so one can check the Utreexo proof faster than going through WorkForest. Ported from #400.

utreexo: verify method

---

demo/src/net.rs
p2p/examples/chatter.rs
p2p/src/node.rs
p2p/src/peer.rs

Later we should make it either a generic type encoded/decoded right by the p2p lib, or a Bytes buffer for avoiding unnecessary copies.

p2p: change type of the custom message to binary buffer

---

p2p/src/cybershake.rs
p2p/src/node.rs
p2p/src/peer.rs

The `cybershake::Error` is mostly used where io::Error is needed, and so for a few places where we fail to decode a Ristretto point or the ciphertext is damaged we simply report `InvalidData`. After all, cybershake is an I/O middleware.

p2p: remove cybershake::Error

---

.travis.yml

Some remote links don't load sometimes, causing very annoying CI failures. We can still check them manually from time to time, using the script, but that's causing more trouble in day-to-day development than reasonable.

travis CI: do not check remote links as they are often broken

---

.travis.yml
readerwriter/.gitignore
readerwriter/Cargo.toml
readerwriter/src/bytes_ext.rs
readerwriter/src/bytes_support.rs
readerwriter/src/lib.rs
readerwriter/src/merlin_ext.rs
readerwriter/src/merlin_support.rs
readerwriter/src/reader.rs
readerwriter/src/writer.rs
zkvm/Cargo.toml
zkvm/src/contract.rs
zkvm/src/debug.rs
zkvm/src/encoding.rs
zkvm/src/merkle.rs
zkvm/src/ops.rs
zkvm/src/predicate.rs
zkvm/src/program.rs
zkvm/src/tx.rs
zkvm/src/types.rs
zkvm/src/verifier.rs
zkvm/src/vm.rs

This is an implementation of #424

readerwriter: new crate to unify encoding in zkvm/blockchain/p2p

---

zkvm/src/constraints.rs

A small fixup for the MockCS after we've made a breaking change to the R1CS metrics API: https://github.com/dalek-cryptography/bulletproofs/pull/322

zkvm: fix for r1cs update

---

blockchain/src/codec.rs
demo/src/net.rs
p2p/examples/chatter.rs
p2p/src/codec.rs
readerwriter/src/reader.rs
zkvm/src/contract.rs
zkvm/src/merkle.rs
zkvm/src/ops.rs
zkvm/src/tx.rs

1. Rename `read_vec` to `read_bytes`.
2. Rename `read_vec_with` to `read_vec`.
3. Remove min-item-length parameter and avoid pre-allocation of the vector to simplify the API.
closes #434

readerwriter: simplify vector-reading API

---

accounts/Cargo.toml
accounts/src/address.rs
accounts/src/derivation.rs
accounts/src/lib.rs
zkvm/src/contract.rs
zkvm/src/types.rs

This introduces an **address API**: ability to create a short and friendly one-time-use string to receive money in encrypted form:
```
test1uq90n36dnmdca0xpvr8we974x89adc54d70fzc4ca8k6yc8g9epca0ntey5jx9jk3q70cwzzjz6jgwx8zm6ezff4ss0f9a5p2junsnc480zqt
```
* String format uses [bech32](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki).
* Prefix of the string (`test` in the example above) is customizable: it can be _versioned_ and also separates addresses between the networks/ledgers.
* The address contains two pubkeys: one for the predicate, another for encryption. Both are derived from the account Xpub in a way that allows user to decrypt incoming payments with just Xpub, without having access to the private key of the predicate.
* Sender embeds a 73-byte ciphertext string in …

accounts: non-interactive payment addresses

---

demo/src/schema.rs

Fix the formatting of a schema file that gets fixed up whenever running
diesel database reset.
Every time diesel database reset is executed it (or something) fixes the
formatting of schema.rs. It causes a diff to appear which is
inconvenient.

demo: fix formatting of schema file causing diff

---

demo/src/handlers.rs
demo/templates/nodes/show.html.tera

Change where the account sequence and xpub are retrieved from on the node/show page.
The account package was refactored in dffffb2fe0bd85467479e9e8422d63cc973e9a14 and that resulted in the sequence moving from the account object to the wallet object, and the xpub is no longer stored in an object that has been serialized.
Updating where the sequence should come from is trivial.
Updating where the xpub could be done a couple of ways. We could expand the JSON serialized wallet to include it, but that requires changing the account package and the xpub would only be added to the struct for the demo, so instead I added it to the context for rendering the template separately to the wallet. I could see reasons to go both ways though.
Fix #476

demo: fix rendering of account (node/show template)

---

accounts/Cargo.toml
accounts/src/address.rs
accounts/src/derivation.rs
accounts/src/lib.rs
accounts/src/receiver.rs
accounts/src/tests.rs
blockchain/src/block.rs
blockchain/src/mempool.rs
blockchain/src/protocol.rs
blockchain/src/state.rs
blockchain/src/tests.rs
blockchain/src/utreexo/forest.rs
demo/src/handlers.rs
demo/src/schema.rs
node/Cargo.toml
node/src/json.rs
node/src/main.rs
node/src/ui/bc_annotations.rs
node/src/ui/mod.rs
node/src/wallet.rs
token/Cargo.toml
token/src/derivation.rs
token/src/lib.rs
token/src/token.rs
zkvm/src/contract.rs
zkvm/src/errors.rs
zkvm/src/predicate.rs
zkvm/src/tx.rs
zkvm/src/types.rs

This adds wallet logic. So we can manage spendable utxos.
The entire wallet data is a list of unexpired receivers, annotated txs and spendable utxos with different states.
For simplicity, we'll store the entire thing in a single file and load it as a whole. Later, we'll probably need to keep it in a sqlite or at least separate files: for pending txs, for spendable utxos, for archived txs, etc. Make sure the storage is completely separate from the blockchain data.

node/wallet: new module for handling accounts and spendable utxos

---

node/src/wallet.rs
zkvm/src/tx.rs
zkvm/src/vm.rs

Adds intermediate type `BuiltTx` that contains all tx data, utreexo proofs, and signing instructions (derivation sequences and aliases). Then, the `BuiltTx::sign` method takes an Xprv, derives all the keys according to the instructions and returns a fully signed `BlockTx`, that can be published.
Closes #485

node: separate signing from building

---

demo/src/account.rs
demo/src/schema.rs
token/src/token.rs
zkvm/docs/zkvm-spec.md
zkvm/src/debug.rs
zkvm/src/ops.rs
zkvm/src/program.rs
zkvm/src/vm.rs
zkvm/tests/zkvm.rs

Closes #482.
* `const` -> `scalar` for instantiating clear-text scalar values
* `var` -> `commit` for high-level variables tied to Pedersen commitments ("external facts")
* unchanged: `alloc` for low-level variables not tied to any external commitments.

zkvm: rename CS variable operations

---

zkvm/docs/zkvm-spec.md
zkvm/src/debug.rs
zkvm/src/ops.rs
zkvm/src/program.rs
zkvm/src/vm.rs
zkvm/tests/zkvm.rs

This opcode is a lightweight variant of `call`, needed for payment channel implementation (#496).

zkvm: eval opcode
