- zkvm/spec/ZkVM.md
This adds a payment channel example to the spec.
> ZkVM: payment channel example

- zkvm/src/vm.rs
> zkvm: add `neg` instruction

- zkvm/src/contract.rs
- zkvm/src/vm.rs
- zkvm/tests/zkvm.rs
https://github.com/interstellar/slingshot/issues/78 tests 2-6, in progress
> zkvm: add spending tests

- spacesuit/src/value.rs
Adds missing doc to `pub fn to_scalar`
> spacesuit: add missing doc

- zkvm/src/types.rs
- zkvm/src/vm.rs
> zkvm: implement Mul for ScalarWitness

- spacesuit/src/lib.rs
- spacesuit/src/mix.rs
- spacesuit/src/range_proof.rs
- spacesuit/src/signed_integer.rs
- spacesuit/src/value.rs
Also added a few overflow tests for SignedInteger.
> spacesuit: move SignedInteger into a separate module

- zkvm/src/scalar_witness.rs
Adds scalar witness tests for arithmetic and checking overflow protection using scalars
> zkvm/scalar_witness: add scalar witness tests

- slidechain/cmd/slidechaind/slidechaind.go
- slidechain/custodian.go
- slidechain/export_test.go
- slidechain/import.go
- slidechain/slidechain_test.go
- slidechain/submit.go
Makes the expected interval between blocks upon submitting a transaction to TxVM customizable.
> slidechain: make block interval customizable

- keytree/Cargo.toml
- keytree/src/lib.rs
This implements https://github.com/interstellar/slingshot/blob/main/keytree/keytree.md#convert-xprv-to-xpub
>  keytree: generate Xpub from Xprv

- zkvm/docs/zkvm-spec.md
- zkvm/src/vm.rs
> zkvm: implement `call` instruction

- keytree/src/transcript.rs
> keytree: add extension trait to Merlin

- spacesuit/src/bit_range.rs
- spacesuit/src/cloak.rs
- spacesuit/src/lib.rs
- spacesuit/src/range_proof.rs
- zkvm/docs/zkvm-spec.md
- zkvm/src/errors.rs
- zkvm/src/ops.rs
- zkvm/src/vm.rs
- zkvm/tests/zkvm.rs
> spacesuit: implement type-safe `BitRange` for range proofs

- zkvm/src/constraints.rs
- zkvm/src/errors.rs
- zkvm/src/types.rs
- zkvm/src/vm.rs
> zkvm: Implement `unblind` Instruction

- zkvm/src/vm.rs
Implements borrow instruction. Closes #152.
> zkvm: implements borrow

- zkvm/src/lib.rs
- zkvm/src/merkle.rs
- zkvm/src/txlog.rs
> zkvm/merkle: factor out merkle proofs into separate module

- zkvm/docs/zkvm-spec.md
- zkvm/src/ops.rs
- zkvm/src/vm.rs
Removes the qty and flavor instructions. Closes #153.
> zkvm: removes qty and flavor instructions

- keytree/src/lib.rs
After all of the rigamarole of https://github.com/interstellar/slingshot/pull/220,
Oleg realized that transcripts are insufficient for serializing keys. 
(We had de facto been storing the compressed point inside
the transcript, but we couldn't get it back out again when serializing.) 
So instead we will store a compressed points instead of transcripts.
(We'll create transcripts on the fly when deriving child keys.)
> keytree: store precompressed points instead of transcripts

- zkvm/docs/zkvm-spec.md
- zkvm/src/ops.rs
- zkvm/src/predicate.rs
- zkvm/src/vm.rs
> zkvm: commit blinding factor with program in predicate tree

- zkvm/docs/zkvm-spec.md
- zkvm/src/vm.rs
> zkvm: simplify `unblind`

- zkvm/src/errors.rs
- zkvm/src/signature/counterparty.rs
- zkvm/src/signature/multikey.rs
- zkvm/src/signature/musig.rs
Addresses part of https://github.com/interstellar/slingshot/issues/92.
> zkvm/src/signature: add Signature::sign_single, handle 1-key Multikey specially

- zkvm/src/lib.rs
- zkvm/src/signature/mod.rs
- zkvm/src/signature/musig.rs
- zkvm/src/signature/signer.rs
Also cleans up warnings and missing docs.
> musig: use &mut Transcript comme il faut

- zkvm/tests/zkvm.rs
Adding tests that exercise predicate disjunction signing + program predicates (w/ some slight cleanups)
> zkvm/tests: add predicate tests

- zkvm/src/blockchain/block.rs
- zkvm/src/blockchain/state.rs
- zkvm/src/program.rs
Implements the `make block` procedure from the spec
> zkvm/blockchain: make block

- zkvm/docs/zkvm-spec.md
- zkvm/src/prover.rs
- zkvm/src/verifier.rs
> zkvm: commit txid to the r1cs proof

- zkvm/src/constraints.rs
- zkvm/src/contract.rs
- zkvm/src/encoding.rs
- zkvm/src/ops.rs
- zkvm/src/predicate.rs
- zkvm/src/program.rs
- zkvm/src/prover.rs
- zkvm/src/scalar_witness.rs
- zkvm/src/tx.rs
- zkvm/src/types.rs
Resolves #305 
Implemented Encodable trait for encode() and serialized_length()
> zkvm: Implement Encodable trait

- README.md
- zkvm/README.md
> zkvm: more usable links in the README

- zkvm/docs/zkvm-spec.md
Addresses part of https://github.com/stellar/slingshot/issues/309.
> zkvm/docs: rename data type to string type in spec

- zkvm/docs/zkvm-spec.md
- zkvm/src/blockchain/tests.rs
- zkvm/src/contract.rs
- zkvm/src/errors.rs
- zkvm/src/lib.rs
- zkvm/src/ops.rs
- zkvm/src/program.rs
- zkvm/src/types.rs
- zkvm/src/vm.rs
- zkvm/tests/zkvm.rs
> zkvm: rename Data to String

- zkvm/docs/zkvm-spec.md
> zkvm: clarify that only portable items are allowed in Contracts

- accounts/src/tests.rs
- zkvm/src/blockchain/state.rs
- zkvm/src/blockchain/tests.rs
- zkvm/src/utreexo/forest.rs
- zkvm/src/utreexo/mod.rs
- zkvm/src/utreexo/nodes.rs
- zkvm/src/utreexo/tests.rs
This makes it possible to serialize blockchain state. Some structs are suboptimally serialized, which is TBD for the future improvements.
> zkvm: serde support for Utreexo and blockchain state

- demo/src/main.rs
- demo/src/nodes.rs
- demo/static/main.css
- demo/templates/assets/show.html.tera
- demo/templates/network/block_show.html.tera
- demo/templates/network/mempool.html.tera
- demo/templates/nodes/show.html.tera
> demo: cleaner tx presentation and the initial asset distribution

- accounts/src/tests.rs
- demo/src/account.rs
- token/src/token.rs
- zkvm/src/blockchain/tests.rs
- zkvm/src/predicate.rs
- zkvm/src/program.rs
- zkvm/tests/zkvm.rs
> Change return signature of Program::build from `&mut Program` to ()

- accounts/src/tests.rs
- blockchain/Cargo.toml
- blockchain/src/block.rs
- blockchain/src/errors.rs
- blockchain/src/mempool.rs
- blockchain/src/protocol.rs
- blockchain/src/shortid.rs
- blockchain/src/state.rs
- blockchain/src/tests.rs
- blockchain/src/utreexo/forest.rs
- demo/src/handlers.rs
- starsig/Cargo.toml
- starsig/src/signature.rs
This finishes up stubnet protocol implementation: 
1. mempool sync between peers
2. blockchain download
3. creating and signing new blocks
> blockchain: stubnet implementation

- .github/workflows/check-crates.yml
This should make CI builds faster.
> CI: no optimizations for bench builds

- demo/Cargo.toml
- demo/README.md
Solution discovered by @p0lunin
> demo: add libsqlite3-sys to fix windows builds

- blockchain/src/block.rs
- blockchain/src/codec.rs
- zkvm/src/contract.rs
- zkvm/src/encoding.rs
- zkvm/src/errors.rs
- zkvm/src/ops.rs
- zkvm/src/tx.rs
- zkvm/src/vm.rs
> zkvm: impl Decodable for Tx

- blockchain/src/codec.rs
> blockchain: refactor msg types

- blockchain/src/block.rs
- blockchain/src/codec.rs
- demo/src/mempool.rs
- demo/src/net.rs
- demo/src/schema.rs
- p2p/examples/chatter.rs
- p2p/src/codec.rs
- readerwriter/src/codable.rs
- readerwriter/src/lib.rs
- zkvm/src/constraints.rs
- zkvm/src/contract.rs
- zkvm/src/encoding.rs
- zkvm/src/merkle.rs
- zkvm/src/ops.rs
- zkvm/src/predicate.rs
- zkvm/src/program.rs
- zkvm/src/scalar_witness.rs
- zkvm/src/tx.rs
- zkvm/src/types.rs
- zkvm/src/verifier.rs
> readerwriter: factor out ExactSizeEncodable

- p2p/src/cybershake.rs
> p2p: cybershake uses single DH instance with blinded ID keys

- accounts/src/tests.rs
- demo/src/account.rs
- zkvm/docs/zkvm-spec.md
- zkvm/src/contract.rs
- zkvm/src/types.rs
- zkvm/src/vm.rs
- zkvm/tests/zkvm.rs
> zkvm: reverse order of cloak outputs

- zkvm/src/types.rs
- zkvm/src/vm.rs
- zkvm/tests/zkvm.rs
> zkvm: cleanup Value::assignment API

- accounts/Cargo.toml
- blockchain/Cargo.toml
- blockchain/src/errors.rs
- blockchain/src/lib.rs
- blockchain/src/utreexo/forest.rs
- musig/Cargo.toml
- musig/src/errors.rs
- musig/src/lib.rs
- spacesuit/Cargo.toml
- starsig/Cargo.toml
- starsig/src/errors.rs
- starsig/src/lib.rs
- token/Cargo.toml
- zkvm/Cargo.toml
- zkvm/src/errors.rs
- zkvm/src/lib.rs
> Replace `failure` with `thiserror`

- blockchain/src/protocol.rs
- demo/src/net.rs
- node/src/bc.rs
- node/src/config.rs
- p2p/examples/chatter.rs
- p2p/src/node.rs
This prepares a skeleton for integrating blockchain state machine and p2p stack.
> node: integrating blockchain into p2p stack
